# Faster builds on setup when not using sudo.
sudo: false

# Cache nodemodules for faster builds
cache:
  directories:
    - node_modules

language: node_js

node_js:
  - '8'
  - '4'

script: npm run test-ci
after_success: npm run coveralls
